blog/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

AUTH_PATTERNS = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='blog/auth/logout.html'
    ), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
]

EDITORCP_PATTERNS = [
    path('', views.editorcp_index, name='editorcp'),
    path('<str:success>', views.editorcp_index, name='editorcp'),
    path('entries/', views.EditorcpListEntries.as_view(), name='list_entries'),
    path('entries/new/', views.EditorcpCreateEntry.as_view(), name='create_entry'),
    path('entries/<int:pk>/', views.EditorcpEditEntry.as_view(), name='edit_entry'),
    path('entries/<int:pk>/remove/', views.EditorcpDeleteEntry.as_view(), name='delete_entry'),
    path('tags/', views.EditorcpListTags.as_view(), name='list_tags'),
    path('tags/new/', views.EditorcpCreateTag.as_view(), name='create_tag'),
    path('tags/<int:pk>/', views.EditorcpEditTag.as_view(), name='edit_tag'),
    path('tags/<int:pk>/remove/', views.EditorcpDeleteTag.as_view(), name='delete_tag'),
    path('important_entries/', views.EditorcpListImportantEntries.as_view(), name='list_important_entries'),
    path('important_entries/new/', views.EditorcpCreateImportantEntry.as_view(), name='create_important_entry'),
    path('important_entries/<int:pk>/', views.EditorcpEditImportantEntry.as_view(), name='edit_important_entry'),
    path('important_entries/<int:pk>/remove/', views.EditorcpDeleteImportantEntry.as_view(), name='delete_important_entry'),
]

app_name = 'blog'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('about/', views.blog_about, name='about'),
    path('contact/', views.blog_contact, name='contact'),
    path('tag/<int:pk>/', views.BlogTag.as_view(), name='view_tag'),
    path('user/<int:pk>/', views.BlogUser.as_view(), name='view_user'),
    path('entry/<int:pk>/<slug:slug>/', views.blog_entry, name='view_entry'),
    path('', include(AUTH_PATTERNS)),
    path('editorcp/', include(EDITORCP_PATTERNS)),
]

simpleblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls)
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone


class Tag(models.Model):
    """Tag or keyword that will be added to an entry to describe it."""
    name = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):
        return f'{self.name}: {self.description[:10]}...'


class Entry(models.Model):
    """Any entry of the blog."""
    title = models.CharField(max_length=50)
    content = models.TextField()
    summary = models.TextField(
        help_text='A very short summary that will help your visitors to understand about what '
                  'the article is. This text will appear below your entry title and on the '
                  'carousel if it is marked as important.'
    )
    pub_date = models.DateTimeField('date published', default=timezone.now)
    tag = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return f'{self.title} by {self.author}: {self.summary[:10]}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        try:
            self.important_entry.delete()
        except AttributeError:
            pass
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'entries'


class Profile(models.Model):
    """Profile that will have extra info about the user."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_editor = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} is ' + ('not ' if not self.is_editor else '') + 'an editor'

    def can_access_ecp(self):
        return self.user.is_staff or self.user.is_superuser or self.is_editor


class ImportantEntry(models.Model):
    """Important entries that will be displayed in the carousel."""
    entry = models.OneToOneField(Entry, on_delete=models.CASCADE)
    image_name = models.CharField(
        max_length=50,
        help_text='The direction and name of the image located in '
                  'the static/blog/images folder of the blog app.'
    )
    active = models.BooleanField(
        default=True,
        help_text='Whether the entry will be displayed in the '
                  'carousel or it will be hidden until you active it.'
    )

    def get_image_url(self):
        return f'blog/images/{self.image_name}'

    class Meta:
        verbose_name_plural = 'important entries'

blog/views.py
from django.views import generic
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Entry, Profile, Tag, ImportantEntry


class Index(generic.ListView):
    template_name = 'blog/content/index.html'
    context_object_name = 'latest_entries_list'

    def get_queryset(self):
        return Entry.objects.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['active_navbar'] = 'home'
        context['important_entries'] = ImportantEntry.objects.filter(
            active=True
        )
        return context


class Login(auth_views.LoginView):
    template_name = 'blog/auth/login.html'
    redirect_authenticated_user = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_navbar'] = 'login'
        return context


class Signup(generic.edit.FormView):
    template_name = 'blog/auth/signup.html'
    form_class = UserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect('blog:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_navbar'] = 'signup'
        return context


def editorcp_check(user):
    if not user.is_authenticated:
        return False

    try:
        return user.profile.can_access_ecp()
    except AttributeError:
        return user.is_staff or user.is_superuser


def blog_entry(request, pk, slug):
    entry = Entry.objects.get(pk=pk)

    if entry.slug != slug:
        return redirect('blog:view_entry', pk=pk, slug=entry.slug)

    context = {
        'entry': entry,
        'important_entries': ImportantEntry.objects.filter(active=True),
    }
    return render(request, 'blog/content/entry.html', context)


class BlogTag(generic.DetailView):
    model = Tag
    template_name = 'blog/content/tag.html'


class BlogUser(generic.DetailView):
    model = User
    template_name = 'blog/content/user.html'


def blog_about(request):
    return render(request, 'blog/content/about.html', {'active_navbar': 'about'})


def blog_contact(request):
    return render(request, 'blog/content/contact.html', {'active_navbar': 'contact'})


@user_passes_test(editorcp_check)
def editorcp_index(request, success=None):
    entries = Entry.objects.all()
    tags = Tag.objects.all()
    important_entries = ImportantEntry.objects.all()
    active_important_entries = ImportantEntry.objects.filter(active=True)

    def check_no_entries_created():
        return not entries.count()

    def check_no_tags_created():
        return not tags.count()

    def check_no_important_entries_active():
        return important_entries.count() == 0 or active_important_entries.count() == 0

    alerts = {
        'no_entries_created': {
            'show': check_no_entries_created(),
            'msg': 'You have not created any entry yet. Your blog will appear without '
                   'content until you do it.',
            'type': 'danger',
        },
        'no_tags_created': {
            'show': check_no_tags_created(),
            'msg': 'You have not created any tag yet. This could provoke that your '
                   'visitors are not receiving enough description about your entries.',
            'type': 'warning',
        },
        'no_important_entries': {
            'show': check_no_important_entries_active(),
            'msg': 'You have not set any entry as important. Because of this, the carousel '
                   'of the blog pages will not appear. If you want to make it visible, mark '
                   'an entry as important.',
            'type': 'danger',
        },
    }

    success_message = {
        'entry_created': 'New entry created successfully!',
        'entry_edited': 'Existent entry edited successfully!',
        'entry_deleted': 'Entry deleted successfully!',
        'tag_created': 'New tag created successfully!',
        'tag_edited': 'Existent tag edited successfully!',
        'tag_deleted': 'Tag deleted successfully!',
        'important_entry_created': 'Entry marked as important successfully!',
        'important_entry_edited': 'Existent important entry edited sucessfully!',
        'important_entry_deleted': 'Entry marked as not important successfully!',
    }

    context = {
        'alerts': alerts,
        'success': success_message[success] if success else None
    }

    return render(request, 'blog/editorcp/index.html', context)

class EditorcpCreateEntry(UserPassesTestMixin, generic.edit.CreateView):
    model = Entry
    template_name = 'blog/editorcp/create_entry.html'
    fields = ['title', 'summary', 'content', 'tag']

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.author = self.request.user
        form.save()
        return redirect('blog:editorcp', success='entry_created')

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpListEntries(UserPassesTestMixin, generic.ListView):
    template_name = 'blog/editorcp/list_entries.html'
    context_object_name = 'latest_entries_list'

    def get_queryset(self):
        return Entry.objects.order_by('-pub_date')

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpEditEntry(UserPassesTestMixin, generic.edit.UpdateView):
    template_name = 'blog/editorcp/edit_entry.html'
    model = Entry
    fields = ['title', 'summary', 'content', 'tag']
    success_url = reverse_lazy('blog:editorcp', args=('entry_edited',))

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpDeleteEntry(UserPassesTestMixin, generic.edit.DeleteView):
    template_name = 'blog/editorcp/delete_entry.html'
    model = Entry
    success_url = reverse_lazy('blog:editorcp', args=('entry_deleted',))

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpCreateTag(UserPassesTestMixin, generic.edit.CreateView):
    model = Tag
    template_name = 'blog/editorcp/create_tag.html'
    fields = ['name', 'description']
    success_url = reverse_lazy('blog:editorcp', args=('tag_created',))

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpListTags(UserPassesTestMixin, generic.ListView):
    template_name = 'blog/editorcp/list_tags.html'
    context_object_name = 'tag_list'

    def get_queryset(self):
        return Tag.objects.all()

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpEditTag(UserPassesTestMixin, generic.edit.UpdateView):
    template_name = 'blog/editorcp/edit_tag.html'
    model = Tag
    success_url = reverse_lazy('blog:editorcp', args=('tag_edited',))
    fields = ['name', 'description']

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpDeleteTag(UserPassesTestMixin, generic.edit.DeleteView):
    template_name = 'blog/editorcp/delete_tag.html'
    model = Tag
    success_url = reverse_lazy('blog:editorcp', args=('tag_deleted',))

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpCreateImportantEntry(UserPassesTestMixin, generic.edit.CreateView):
    template_name = 'blog/editorcp/create_important_entry.html'
    model = ImportantEntry
    fields = ['entry', 'image_name']
    success_url = reverse_lazy(
        'blog:editorcp', args=('important_entry_created',))

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpListImportantEntries(UserPassesTestMixin, generic.ListView):
    template_name = 'blog/editorcp/list_important_entries.html'
    context_object_name = 'important_entries_list'

    def get_queryset(self):
        return ImportantEntry.objects.all()

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpEditImportantEntry(UserPassesTestMixin, generic.edit.UpdateView):
    template_name = 'blog/editorcp/edit_important_entry.html'
    model = ImportantEntry
    success_url = reverse_lazy(
        'blog:editorcp', args=('important_entry_edited',))
    fields = ['entry', 'image_name', 'active']

    def test_func(self):
        return editorcp_check(self.request.user)


class EditorcpDeleteImportantEntry(UserPassesTestMixin, generic.edit.DeleteView):
    template_name = 'blog/editorcp/delete_important_entry.html'
    model = ImportantEntry
    success_url = reverse_lazy(
        'blog:editorcp',
        args=('important_entry_deleted',)
    )

    def test_func(self):
        return editorcp_check(self.request.user)

blog/templates/blog/content/about.html
{% extends 'blog/base/content.html' %}

{% block title %}
  About - {{ block.super }}
{% endblock title %}

{% block content %}
  <div class="row">
    <h2 class="section-title col-12 col-xl-8"><span>About Simpleblog</span></h2>
  </div>
  <p class="mt-5 mb-0">Simpleblog is a very simple and open source CMS created by <a href="https://github.com/Aaron23145">Aarón Arriero Peláez.</a></p>
  <p>You can read more about the project in its repo: <a href="https://github.com/Aaron23145/simpleblog-django">Simpleblog Repository</a></p>
{% endblock content %}

blog/templates/blog/content/contact.html
{% extends 'blog/base/content.html' %}

{% block title %}
  Contact - {{ block.super }}
{% endblock title %}

{% block content %}
  <div class="row">
    <h2 class="section-title col-12 col-xl-8"><span>Contact</span></h2>
  </div>
  <p class="mt-5 mb-0">You can contact its creator through <a href="https://github.com/Aaron23145">GitHub</a> or <a href="mailto:aaronarrieropelaez99@gmail.com">sending a mail</a>.</p>
{% endblock content %}

blog/templates/blog/content/entry.html
{% extends 'blog/base/content.html' %}

{% block title %}
  {{ entry.title }} - {{ block.super }}
{% endblock title %}

{% block content %}
  <article>
    <div class="row">
      <h2 class="entry-title col-12 col-xl-8"><span>{{ entry.title }}</span></h2>
      <p class="entry-info col align-self-end">
        At {{ entry.pub_date }} by 
        <a class="entry-author" href="#">{{ entry.author }}</a>
      </p>
    </div>
    <p class="entry-summary">{{ entry.summary }}</p>
    <p>{{ entry.content }}</p>
    <div class="mt-2 text-right">
    {% for tag in entry.tag.all %}
      <button class="btn btn-primary mx-1 btn-sm">{{ tag.name }}</button>
    {% endfor %}
    </div>
  </article>
{% endblock content %}

blog/templates/blog/content/index.html
{% extends 'blog/base/content.html' %}

{% block title %}
  Index - {{ block.super }}
{% endblock title %}

{% block content %}
  <h1 class="d-none">Latest entries</h1>

  {% for entry in latest_entries_list %}
    <article>
      <div class="row">
        <h2 class="entry-title col-12 col-xl-8">
          <a href="{% url 'blog:view_entry' entry.pk entry.slug %}">{{ entry.title }}</a>
        </h2>
        <p class="entry-info col align-self-end">
          At {{ entry.pub_date }} by 
          <a class="entry-author" href="{% url 'blog:view_user' entry.author.pk %}">{{ entry.author }}</a>
        </p>
      </div>
      <p class="entry-summary">{{ entry.summary }}</p>
      {% if entry.content|length >= 2000 %}
        <p class="mb-0">{{ entry.content|truncatechars:2000 }}</p>
        <a href="{% url 'blog:view_entry' entry.pk entry.slug %}">Read more...</a>
      {% else %}
        <p>{{ entry.content|truncatechars:2000 }}</p>
      {% endif %}
      {% if entry.tag.all|length %}
        <div class="my-2 text-right">
        {% for tag in entry.tag.all %}
          <a href="{% url 'blog:view_tag' tag.pk %}" type="button" class="btn btn-primary mt-1 mb-5 btn-sm">{{ tag.name }}</a>
        {% endfor %}
        </div>
      {% endif %}
    </article>
  {% endfor %}
{% endblock content %}

blog/templates/blog/content/tag.html
{% extends 'blog/base/content.html' %}

{% block title %}
  {{ object.name }} -{{ block.super }}
{% endblock title %}

{% block content %}
  <div class="row">
    <h2 class="entry-title col-12 col-xl-8"><span>{{ object.name }}</span></h2>
  </div>
  <p class="mt-5 mb-0">{{ object.description }}</p>
  </div>
{% endblock content %}

blog/templates/blog/content/user.html
{% extends 'blog/base/content.html' %}

{% block title %}
  {{ object.username }} -{{ block.super }}
{% endblock title %}

{% block content %}
  <div class="row">
    <h2 class="entry-title col-12 col-xl-8"><span>{{ object.username }}</span></h2>
  </div>
  {% if object.profile %}
    {% if object.profile.is_editor %}
      <p class="mt-5 mb-0">This user has is_editor set as true.</p>
    {% else %}
      <p class="mt-5 mb-0">This user has is_editor set as false.</p>
    {% endif %}
  {% else %}
    <p class="mt-5 mb-0">User has not a defined profile. That usually happens when you create a user through the createsuperuser command. Try changing its profile in the django admin (for example, change its is_editor to True).</p>
  {% endif %}
  
  </div>
{% endblock content %}